import * as fs from "fs";
import * as path from "path";

import { KB_CANONICAL_TOOL_NAMES } from "../runtime/kb_tool_contract";
import { sha256 } from "../utils/hash";
import type { InstallerSessionRuntimeMetadata } from "./types";

export const SESSION_RUNTIME_AGENT_ID = "llmwiki" as const;
export const SESSION_RUNTIME_PLUGIN_ID = "llmwiki-kb-tools" as const;
export const SESSION_RUNTIME_RELATIVE_PLUGIN_ROOT =
  ".openclaw/extensions/llmwiki-kb-tools" as const;
export const SESSION_RUNTIME_RELATIVE_PLUGIN_INDEX =
  ".openclaw/extensions/llmwiki-kb-tools/index.ts" as const;
export const SESSION_RUNTIME_RELATIVE_PLUGIN_MANIFEST =
  ".openclaw/extensions/llmwiki-kb-tools/openclaw.plugin.json" as const;
export const SESSION_RUNTIME_PLUGIN_ENABLED_CONFIG_PATH =
  "plugins.entries.llmwiki-kb-tools.enabled" as const;
export const SESSION_RUNTIME_PLUGIN_ENTRY_CONFIG_PATH =
  "plugins.entries.llmwiki-kb-tools" as const;
export const SESSION_RUNTIME_PLUGIN_ALLOW_CONFIG_PATH = "plugins.allow" as const;
export const SESSION_RUNTIME_PLUGIN_LOAD_PATHS_CONFIG_PATH =
  "plugins.load.paths" as const;

export interface SessionRuntimeArtifactPaths {
  pluginRoot: string;
  pluginIndexFile: string;
  pluginManifestFile: string;
  pluginEnabledConfigPath: typeof SESSION_RUNTIME_PLUGIN_ENABLED_CONFIG_PATH;
}

export interface RenderedSessionRuntimeArtifact {
  content: string;
  contentHash: string;
}

export interface BuildSessionRuntimeMetadataOptions {
  workspacePath: string;
  kbRoot: string;
  agentId?: string;
  sourcePluginEntrypoint: string;
  sourcePluginManifestPath: string;
  canonicalToolNames?: readonly string[];
  installedAt?: string;
}

export interface MaterializeSessionRuntimeArtifactResult {
  metadata: InstallerSessionRuntimeMetadata;
  createdFiles: string[];
  overwrittenFiles: string[];
  createdDirectories: string[];
}

export interface SessionRuntimeArtifactFingerprint {
  pluginIndexContentHash?: string;
  pluginManifestContentHash?: string;
  missingPaths: string[];
}

export function resolveSessionRuntimeArtifactPaths(
  workspacePath: string
): SessionRuntimeArtifactPaths {
  const normalizedWorkspace = path.resolve(workspacePath);
  return {
    pluginRoot: path.resolve(normalizedWorkspace, SESSION_RUNTIME_RELATIVE_PLUGIN_ROOT),
    pluginIndexFile: path.resolve(normalizedWorkspace, SESSION_RUNTIME_RELATIVE_PLUGIN_INDEX),
    pluginManifestFile: path.resolve(
      normalizedWorkspace,
      SESSION_RUNTIME_RELATIVE_PLUGIN_MANIFEST
    ),
    pluginEnabledConfigPath: SESSION_RUNTIME_PLUGIN_ENABLED_CONFIG_PATH,
  };
}

export function renderSessionRuntimePluginIndex(options: {
  sourcePluginEntrypoint: string;
  kbRoot?: string;
}): RenderedSessionRuntimeArtifact {
  const normalizedEntrypoint = path.resolve(options.sourcePluginEntrypoint);
  const normalizedKbRoot =
    typeof options.kbRoot === "string" && options.kbRoot.trim().length > 0
      ? path.resolve(options.kbRoot)
      : undefined;
  const content =
    normalizedKbRoot === undefined
      ? [
          "// Generated by kb-openclaw-installer. Installer-owned session runtime shim.",
          `module.exports = require(${JSON.stringify(normalizedEntrypoint)});`,
          "",
        ].join("\n")
      : [
          "// Generated by kb-openclaw-installer. Installer-owned session runtime shim.",
          `const plugin = require(${JSON.stringify(normalizedEntrypoint)});`,
          `const pinnedKbRoot = ${JSON.stringify(normalizedKbRoot)};`,
          "function withPinnedKbRoot(fn) {",
          "  const previousKbRoot = process.env.KB_ROOT;",
          "  process.env.KB_ROOT = pinnedKbRoot;",
          "  return Promise.resolve()",
          "    .then(fn)",
          "    .finally(() => {",
          "      if (previousKbRoot === undefined) {",
          "        delete process.env.KB_ROOT;",
          "      } else {",
          "        process.env.KB_ROOT = previousKbRoot;",
          "      }",
          "    });",
          "}",
          "module.exports = {",
          "  ...plugin,",
          "  register(api) {",
          "    return plugin.register({",
          "      ...api,",
          "      registerTool(tool, options) {",
          "        return api.registerTool({",
          "          ...tool,",
          "          execute: (toolCallId, params) => withPinnedKbRoot(() => tool.execute(toolCallId, params)),",
          "        }, options);",
          "      },",
          "    });",
          "  },",
          "};",
          "",
        ].join("\n");

  return {
    content,
    contentHash: sha256(content),
  };
}

export function renderSessionRuntimePluginManifest(options: {
  sourcePluginManifestPath: string;
  canonicalToolNames?: readonly string[];
}): RenderedSessionRuntimeArtifact {
  const normalizedSourceManifestPath = path.resolve(options.sourcePluginManifestPath);
  const sourceManifest = parseSourcePluginManifest(
    normalizedSourceManifestPath,
    fs.readFileSync(normalizedSourceManifestPath, "utf8")
  );
  const content = `${JSON.stringify(sourceManifest, null, 2)}\n`;

  return {
    content,
    contentHash: sha256(content),
  };
}

export function buildSessionRuntimeMetadata(
  options: BuildSessionRuntimeMetadataOptions
): InstallerSessionRuntimeMetadata {
  const sourcePluginEntrypoint = path.resolve(options.sourcePluginEntrypoint);
  const sourcePluginManifestPath = path.resolve(options.sourcePluginManifestPath);
  const kbRoot = path.resolve(options.kbRoot);
  const sourcePluginEntrypointHash = hashRequiredFile(
    sourcePluginEntrypoint,
    "session source plugin entrypoint"
  );
  const sourcePluginManifestHash = hashRequiredFile(
    sourcePluginManifestPath,
    "session source plugin manifest"
  );
  const artifactPaths = resolveSessionRuntimeArtifactPaths(options.workspacePath);
  const renderedIndex = renderSessionRuntimePluginIndex({
    sourcePluginEntrypoint,
    kbRoot,
  });
  const renderedManifest = renderSessionRuntimePluginManifest({
    sourcePluginManifestPath,
    canonicalToolNames: options.canonicalToolNames,
  });

  return {
    runtimeKind: "workspace-openclaw-native-plugin-shim-v1",
    agentId: options.agentId ?? SESSION_RUNTIME_AGENT_ID,
    pluginId: SESSION_RUNTIME_PLUGIN_ID,
    pluginRoot: artifactPaths.pluginRoot,
    pluginIndexFile: artifactPaths.pluginIndexFile,
    pluginIndexContentHash: renderedIndex.contentHash,
    pluginManifestFile: artifactPaths.pluginManifestFile,
    pluginManifestContentHash: renderedManifest.contentHash,
    pluginEnabledConfigPath: artifactPaths.pluginEnabledConfigPath,
    pluginEnabled: true,
    kbRoot,
    sourcePluginEntrypoint,
    sourcePluginEntrypointHash,
    sourcePluginManifestPath,
    sourcePluginManifestHash,
    canonicalToolNames: normalizeCanonicalToolNames(options.canonicalToolNames),
    installedAt: options.installedAt ?? new Date().toISOString(),
  };
}

export function materializeSessionRuntimeArtifacts(
  options: BuildSessionRuntimeMetadataOptions
): MaterializeSessionRuntimeArtifactResult {
  const workspacePath = path.resolve(options.workspacePath);
  assertWorkspaceRootSafeForSessionRuntime(workspacePath);
  const metadata = buildSessionRuntimeMetadata(options);
  assertSessionRuntimePathsWithinWorkspace(workspacePath, metadata);
  assertNoSymlinkInExistingPathChain(workspacePath, metadata.pluginRoot);
  assertNoSymlinkInExistingPathChain(workspacePath, metadata.pluginIndexFile);
  assertNoSymlinkInExistingPathChain(workspacePath, metadata.pluginManifestFile);

  const renderedIndex = renderSessionRuntimePluginIndex({
    sourcePluginEntrypoint: metadata.sourcePluginEntrypoint,
    kbRoot: metadata.kbRoot,
  });
  const renderedManifest = renderSessionRuntimePluginManifest({
    sourcePluginManifestPath: metadata.sourcePluginManifestPath,
    canonicalToolNames: metadata.canonicalToolNames,
  });

  const createdDirectories: string[] = [];
  const createdFiles: string[] = [];
  const overwrittenFiles: string[] = [];

  if (fs.existsSync(metadata.pluginRoot)) {
    const pluginRootLstat = fs.lstatSync(metadata.pluginRoot);
    if (pluginRootLstat.isSymbolicLink()) {
      throw new Error(
        `Session runtime plugin root must not be a symlink: ${metadata.pluginRoot}`
      );
    }
    if (!pluginRootLstat.isDirectory()) {
      throw new Error(
        `Session runtime plugin root is not a directory: ${metadata.pluginRoot}`
      );
    }
  } else {
    fs.mkdirSync(metadata.pluginRoot, { recursive: true });
    createdDirectories.push(metadata.pluginRoot);
  }

  writeArtifactFile({
    filePath: metadata.pluginIndexFile,
    content: renderedIndex.content,
    createdFiles,
    overwrittenFiles,
  });
  writeArtifactFile({
    filePath: metadata.pluginManifestFile,
    content: renderedManifest.content,
    createdFiles,
    overwrittenFiles,
  });

  return {
    metadata,
    createdFiles,
    overwrittenFiles,
    createdDirectories,
  };
}

export function readSessionRuntimeArtifactFingerprint(
  workspacePath: string
): SessionRuntimeArtifactFingerprint {
  const paths = resolveSessionRuntimeArtifactPaths(workspacePath);
  const missingPaths: string[] = [];

  const pluginIndexContentHash = readFileHashIfRegularFile(paths.pluginIndexFile);
  if (!pluginIndexContentHash) {
    missingPaths.push(paths.pluginIndexFile);
  }

  const pluginManifestContentHash = readFileHashIfRegularFile(paths.pluginManifestFile);
  if (!pluginManifestContentHash) {
    missingPaths.push(paths.pluginManifestFile);
  }

  return {
    pluginIndexContentHash,
    pluginManifestContentHash,
    missingPaths,
  };
}

function writeArtifactFile(options: {
  filePath: string;
  content: string;
  createdFiles: string[];
  overwrittenFiles: string[];
}): void {
  const filePath = path.resolve(options.filePath);
  const fileExists = fs.existsSync(filePath);

  if (fileExists) {
    const fileLstat = fs.lstatSync(filePath);
    if (fileLstat.isSymbolicLink()) {
      throw new Error(`Session runtime artifact path must not be a symlink: ${filePath}`);
    }
    if (!fileLstat.isFile()) {
      throw new Error(`Session runtime artifact path is not a regular file: ${filePath}`);
    }
  }

  if (fileExists) {
    options.overwrittenFiles.push(filePath);
  } else {
    options.createdFiles.push(filePath);
  }

  fs.writeFileSync(filePath, options.content, "utf8");
}

function hashRequiredFile(filePath: string, label: string): string {
  if (!fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) {
    throw new Error(`Missing ${label}: ${filePath}`);
  }

  return sha256(fs.readFileSync(filePath, "utf8"));
}

function readFileHashIfRegularFile(filePath: string): string | undefined {
  if (!fs.existsSync(filePath)) {
    return undefined;
  }

  if (!fs.statSync(filePath).isFile()) {
    return undefined;
  }

  return sha256(fs.readFileSync(filePath, "utf8"));
}

function normalizeCanonicalToolNames(
  canonicalToolNames: readonly string[] | undefined
): string[] {
  const toolNames = canonicalToolNames
    ? [...canonicalToolNames]
    : [...KB_CANONICAL_TOOL_NAMES];

  return [...new Set(toolNames)].sort((left, right) => left.localeCompare(right));
}

function parseSourcePluginManifest(
  manifestPath: string,
  rawContent: string
): Record<string, unknown> {
  let parsed: unknown;
  try {
    parsed = JSON.parse(rawContent);
  } catch (error) {
    throw new Error(
      `Failed to parse source plugin manifest JSON at ${manifestPath}: ${
        error instanceof Error ? error.message : String(error)
      }`
    );
  }

  if (!isRecord(parsed)) {
    throw new Error(`Source plugin manifest must be an object: ${manifestPath}`);
  }

  if (typeof parsed.id !== "string" || parsed.id.length === 0) {
    throw new Error(`Source plugin manifest must include non-empty string id: ${manifestPath}`);
  }

  if (parsed.id !== SESSION_RUNTIME_PLUGIN_ID) {
    throw new Error(
      `Source plugin manifest id mismatch. expected=${SESSION_RUNTIME_PLUGIN_ID} actual=${parsed.id}`
    );
  }

  if (!("configSchema" in parsed) || !isRecord(parsed.configSchema)) {
    throw new Error(
      `Source plugin manifest must include object configSchema for official runtime loading: ${manifestPath}`
    );
  }

  return parsed;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function assertWorkspaceRootSafeForSessionRuntime(workspacePath: string): void {
  if (!fs.existsSync(workspacePath)) {
    throw new Error(`Workspace path does not exist: ${workspacePath}`);
  }

  const workspaceLstat = fs.lstatSync(workspacePath);
  if (workspaceLstat.isSymbolicLink()) {
    throw new Error(`Workspace root must not be a symlink: ${workspacePath}`);
  }

  if (!workspaceLstat.isDirectory()) {
    throw new Error(`Workspace path is not a directory: ${workspacePath}`);
  }
}

function assertSessionRuntimePathsWithinWorkspace(
  workspacePath: string,
  metadata: InstallerSessionRuntimeMetadata
): void {
  const requiredPaths = [metadata.pluginRoot, metadata.pluginIndexFile, metadata.pluginManifestFile];
  for (const requiredPath of requiredPaths) {
    if (!isPathInside(workspacePath, requiredPath)) {
      throw new Error(
        `Session runtime path points outside workspace ownership scope: ${requiredPath}`
      );
    }
  }
}

function assertNoSymlinkInExistingPathChain(
  rootPath: string,
  targetPath: string
): void {
  const normalizedRoot = path.resolve(rootPath);
  const normalizedTarget = path.resolve(targetPath);

  if (!isPathInside(normalizedRoot, normalizedTarget)) {
    throw new Error(`Path is outside workspace ownership scope: ${normalizedTarget}`);
  }

  let currentPath = normalizedRoot;
  const relativeParts = path.relative(normalizedRoot, normalizedTarget).split(path.sep);

  for (const part of relativeParts) {
    if (!part || part === ".") {
      continue;
    }

    currentPath = path.resolve(currentPath, part);
    if (!fs.existsSync(currentPath)) {
      break;
    }

    const candidateLstat = fs.lstatSync(currentPath);
    if (candidateLstat.isSymbolicLink()) {
      throw new Error(`Session runtime path chain must not include symlinks: ${currentPath}`);
    }
  }
}

function isPathInside(rootPath: string, targetPath: string): boolean {
  const normalizedRoot = path.resolve(rootPath);
  const normalizedTarget = path.resolve(targetPath);
  return (
    normalizedTarget === normalizedRoot ||
    normalizedTarget.startsWith(`${normalizedRoot}${path.sep}`)
  );
}
